Modules/PressModule.HMI/Pages/Event/Events/PressModule/DambarCheckNotOk.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Platform.Lib;
using PressModule.Application;
using PressModule.Application.SubProcesses;

namespace PressModule.Pages
{
    [BindProperties]
    public class DambarCheckNotOk : PageModel
    {
        private readonly LineControl.Application.LineControl mLineControl = LineControl.Application.LineControl.Instance;
        private readonly PressModule.Application.PressModule mPressModule = PressModule.Application.PressModule.Instance;

        public void OnPostRetry()
        {
            Dambar.RetryCommand();
        }

        public void OnPostStop()
        {
            mLineControl.Stop();
            mPressModule.Stop();
        }

        public void OnPostRemovedMaterial()
        {
            var deviceId = mPressModule.MaterialTracking.GetPressPositionId((int)DeviceLocation.Dambar);
            mPressModule.SubProcesses.Dambar.RemoveMaterialCommand(deviceId);
        }

        public JsonResult OnPostGetState()
        {
            return new JsonResult(new {state = ((State)mPressModule.State).ToString()});
        }
    }
}

Modules/PressModule.HMI/Pages/Event/Events/PressModule/IndexHandlerIndexerFailedToPickUpProductAtDambar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Platform.Lib;
using PressModule.Application;

namespace PressModule.Pages
{
    [BindProperties]
    public class IndexHandlerIndexerFailedToPickUpProductAtDambar : PageModel
    {
        private readonly LineControl.Application.LineControl mLineControl;
        private readonly PressModule.Application.PressModule mPressModule;

        public IndexHandlerIndexerFailedToPickUpProductAtDambar(LineControl.Application.LineControl lineControl, PressModule.Application.PressModule pressModule)
        {
            mLineControl = lineControl;
            mPressModule = pressModule;
        }
        public void OnPostStop()
        {
            mLineControl.Stop();
            mPressModule.Stop();
        }

        public void OnPostRemovedMaterial()
        {
            var id = mPressModule.MaterialTracking.GetPressPositionId((int)DeviceLocation.Dambar);
            mPressModule.SubProcesses.IndexHandler.ExecuteRemoveDeviceCommand(id);
        }

        public JsonResult OnPostGetState()
        {
            return new JsonResult(new {state = ((State)mPressModule.State).ToString()});
        }
    }
}

Modules/PressModule.HMI/Pages/Event/Events/PressModule/IndexHandlerIndexerFailedToPickUpProductAtForm.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Platform.Lib;
using PressModule.Application;

namespace PressModule.Pages
{
    [BindProperties]
    public class IndexHandlerIndexerFailedToPickUpProductAtForm : PageModel
    {
        private readonly LineControl.Application.LineControl mLineControl;
        private readonly PressModule.Application.PressModule mPressModule;

        public IndexHandlerIndexerFailedToPickUpProductAtForm(LineControl.Application.LineControl lineControl, PressModule.Application.PressModule pressModule)
        {
            mLineControl = lineControl;
            mPressModule = pressModule;
        }
        public void OnPostStop()
        {
            mLineControl.Stop();
            mPressModule.Stop();   
        }

        public void OnPostRemovedMaterial()
        {
            var id = mPressModule.MaterialTracking.GetPressPositionId((int)DeviceLocation.Form);
            mPressModule.SubProcesses.IndexHandler.ExecuteRemoveDeviceCommand(id);
        }

        public JsonResult OnPostGetState()
        {
            return new JsonResult(new {state = ((State)mPressModule.State).ToString()});
        }
    }
}

Modules/PressModule.HMI/Pages/Event/Events/PressModule/IndexHandlerIndexerFailedToPickUpProductAtInfeed.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Platform.Lib;
using PressModule.Application;

namespace PressModule.Pages
{
    [BindProperties]
    public class IndexHandlerIndexerFailedToPickUpProductAtInfeed : PageModel
    {
        private readonly LineControl.Application.LineControl mLineControl;
        private readonly PressModule.Application.PressModule mPressModule;

        public IndexHandlerIndexerFailedToPickUpProductAtInfeed(LineControl.Application.LineControl lineControl, PressModule.Application.PressModule pressModule)
        {
            mLineControl = lineControl;
            mPressModule = pressModule;
        }
        public void OnPostStop()
        {
            mLineControl.Stop();
            mPressModule.Stop();
        }

        public void OnPostRemovedMaterial()
        {
            var id = mPressModule.MaterialTracking.GetPressPositionId((int)DeviceLocation.Infeed);
            mPressModule.SubProcesses.IndexHandler.ExecuteRemoveLeadframeCommand(id);
        }

        public JsonResult OnPostGetState()
        {
            return new JsonResult(new {state = ((State)mPressModule.State).ToString()});
        }
    }
}

Modules/PressModule.HMI/Pages/Event/Events/PressModule/IndexHandlerIndexerFailedToPickUpProductAtTrim.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Platform.Lib;
using PressModule.Application;

namespace PressModule.Pages
{
    [BindProperties]
    public class IndexHandlerIndexerFailedToPickUpProductAtTrim : PageModel
    {
        private readonly LineControl.Application.LineControl mLineControl;
        private readonly PressModule.Application.PressModule mPressModule;

        public IndexHandlerIndexerFailedToPickUpProductAtTrim(LineControl.Application.LineControl lineControl, PressModule.Application.PressModule pressModule)
        {
            mLineControl = lineControl;
            mPressModule = pressModule;
        }
        public void OnPostStop()
        {
            mLineControl.Stop();
            mPressModule.Stop();
        }

        public void OnPostRemovedMaterial()
        {
            var id = mPressModule.MaterialTracking.GetPressPositionId((int)DeviceLocation.Trim);
            mPressModule.SubProcesses.IndexHandler.ExecuteRemoveLeadframeCommand(id);
        }

        public JsonResult OnPostGetState()
        {
            return new JsonResult(new {state = ((State)mPressModule.State).ToString()});
        }
    }
}

Modules/PressModule.HMI/Pages/Event/Events/PressModule/IndexHandlerIndexerFailedToPickUpProductAtWasteTable.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Platform.Lib;
using PressModule.Application;

namespace PressModule.Pages
{
    [BindProperties]
    public class IndexHandlerIndexerFailedToPickUpProductAtWasteTable : PageModel
    {
        private readonly LineControl.Application.LineControl mLineControl;
        private readonly PressModule.Application.PressModule mPressModule;

        public IndexHandlerIndexerFailedToPickUpProductAtWasteTable(LineControl.Application.LineControl lineControl, PressModule.Application.PressModule pressModule)
        {
            mLineControl = lineControl;
            mPressModule = pressModule;
        }
        public void OnPostStop()
        {
            mLineControl.Stop();
            mPressModule.Stop();
        }

        public void OnPostRemovedMaterial()
        {
            var id = mPressModule.MaterialTracking.GetPressPositionId((int)DeviceLocation.WasteBin);
            mPressModule.SubProcesses.IndexHandler.ExecuteRemoveDeviceCommand(id);
        }

        public JsonResult OnPostGetState()
        {
            return new JsonResult(new {state = ((State)mPressModule.State).ToString()});
        }
    }
}

Modules/PressModule.HMI/Pages/Setup/PressModule/SetupPressModule.cshtml.cs
using Authorization.Lib;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Platform.HMI.Resources;
using Platform.Lib;
using Power_X1_iCT.Model;
using PressModule.Updater;
using System;
using System.Collections.Generic;


namespace Power_X1_iCT.Pages.Setup
{
    [BindProperties]
    [Authorize(Policy = SetupPolicy.Name)]
    public class SetupPressModuleModel : PageModel
    {
        private readonly ILogger mLog;
        private readonly PressModuleUpdater mUpdater;

        private PressModule.Application.PressModule mPressModule = PressModule.Application.PressModule.Instance;

        public PressModuleSettingsModel PressModuleSettingsModel { get; set; }
        public TrimmingSettingsModel TrimmingSettingsModel { get; set; }
        public FormingSettingsModel FormingSettingsModel { get; set; }
        public WasteHandlerSettingsModel WasteHandlerSettingsModel { get; set; }
        public bool SimulationEnabled { get; set; }
        public bool IsRunningProduction { get; set; }

        public SetupPressModuleModel(PressModuleUpdater pressModuleUpdater, ILogger<SetupPressModuleModel> logger)
        {
            mLog = logger;
            mUpdater = pressModuleUpdater;
            PressModuleSettingsModel = new PressModuleSettingsModel();
            TrimmingSettingsModel = new TrimmingSettingsModel();
            FormingSettingsModel = new FormingSettingsModel();
            WasteHandlerSettingsModel = new WasteHandlerSettingsModel();

            mPressModule.SimulationChanged += PressModule_SimulationChanged;
            PressModule_SimulationChanged(this, mPressModule.InSimulation);
        }

        private void PressModule_SimulationChanged(object? sender, bool e)
        {
            SimulationEnabled = e;
        }

        public JsonResult OnPostGetState()
        {
            return new JsonResult(new { state = ((State)mPressModule.State).ToString() });
        }

        public JsonResult OnPostGetStatusses()
        {
            return mUpdater.GetStatusses();
        }

        public JsonResult OnPostGetSimulationEnabled()
        {
            return new JsonResult(mPressModule.InSimulation);
        }
        public JsonResult OnPostCanProcessCommands()
        {
            var canProcess = !mPressModule.IsRunningProduction &&
                mPressModule.State == (int)State.Running &&
                mPressModule.Status != (int)Status.Busy;
            return new JsonResult(canProcess);
        }

        #region Main process
        public void OnPostInitialize()
        {
            mLog.LogInformation("OnInitialize");
            mPressModule.Initialize();
        }
        public JsonResult OnPostCanStart()
        {
            return new JsonResult(mPressModule.CanStart());
        }

        public void OnPostStart()
        {
            mLog.LogInformation("OnStart");
            mPressModule.Start();
        }
        public JsonResult OnPostCanStop()
        {
            return new JsonResult(mPressModule.CanStop());
        }

        public void OnPostStop()
        {
            mLog.LogInformation("OnStop");
            mPressModule.Stop();
        }

        public void OnPostTrim()
        {
            mLog.LogInformation("OnTrim");
            mPressModule.ExecuteTrim();
        }

        public void OnPostForm()
        {
            mLog.LogInformation("OnForm");
            mPressModule.ExecuteForm();
        }

        public void OnPostDambar()
        {
            mLog.LogInformation("OnDambar");
            mPressModule.ExecuteDambar();
        }

        public void OnPostIndexerToPick()
        {
            mLog.LogInformation("OnIndexerToPick");
            mPressModule.ExecuteIndexerPick();
        }

        public void OnPostIndexerToPlace()
        {
            mLog.LogInformation("OnIndexerToPlace");
            mPressModule.ExecuteIndexerPlace();
        }

        #endregion

        #region SubProcesses

        [Authorize(Policy = EngineerPolicy.Name)]
        public IActionResult OnPostDownloadTrimmingSettingsToPLC(TrimmingSettingsModel model) => this.CallActionIfAuthorized(() => model.Download());
        [Authorize(Policy = EngineerPolicy.Name)]
        public IActionResult OnPostSaveTrimmingSettings(TrimmingSettingsModel model) => this.CallActionIfAuthorized(() => model.Save(User?.Identity?.Name ?? "N/A"));
        [Authorize(Policy = EngineerPolicy.Name)]
        public IActionResult OnPostRefreshTrimmingSettings(TrimmingSettingsModel model) => this.CallActionIfAuthorized(() => model.RefreshFromRecipe());

        [Authorize(Policy = EngineerPolicy.Name)]
        public IActionResult OnPostDownloadFormingSettingsToPLC(FormingSettingsModel model) => this.CallActionIfAuthorized(() => model.Download());
        [Authorize(Policy = EngineerPolicy.Name)]
        public IActionResult OnPostSaveFormingSettings(FormingSettingsModel model) => this.CallActionIfAuthorized(() => model.Save(User?.Identity?.Name ?? "N/A"));
        [Authorize(Policy = EngineerPolicy.Name)]
        public IActionResult OnPostRefreshFormingSettings(FormingSettingsModel model) => this.CallActionIfAuthorized(() => model.RefreshFromRecipe());

        [Authorize(Policy = EngineerPolicy.Name)]
        public IActionResult OnPostDownloadWasteHandlerSettingsToPLC(WasteHandlerSettingsModel model) => this.CallActionIfAuthorized(() => model.Download());
        [Authorize(Policy = EngineerPolicy.Name)]
        public IActionResult OnPostSaveWasteHandlerSettings(WasteHandlerSettingsModel model) => this.CallActionIfAuthorized(() => model.Save(User?.Identity?.Name ?? "N/A"));
        [Authorize(Policy = EngineerPolicy.Name)]
        public IActionResult OnPostRefreshWasteHandlerSettings(WasteHandlerSettingsModel model) => this.CallActionIfAuthorized(() => model.RefreshFromRecipe());

        public void OnPostResetWasteBinCounter()
        {
            mPressModule.SubProcesses.WasteHandler.ResetWasteHandlerCount();
        }

        public JsonResult OnPostGetWastHandlerBinCount()
        {
            return new JsonResult(mPressModule.SubProcesses.WasteHandler.WasteHandlerCount);
        }

        public void OnPostRemoveTrimTool()
        {
            mPressModule.ExecuteRemoveTrimTool();
        }

        public void OnPostTrimMaintenance()
        {
            mPressModule.ExecuteTrimMaintenance();
        }

        public void OnPostRemoveFormTool()
        {
            mPressModule.ExecuteRemoveFormTool();
        }

        public void OnPostFormMaintenance()
        { 
            mPressModule.ExecuteFormMaintenance();
        }
        #endregion

        #region Resources

        #region Trim

        public void OnPostTrimGoToZ(string input1, string input2)
        {
            mPressModule.Resources.Trim.GoTo(Convert.ToDouble(input1), Convert.ToInt32(input2));
        }


        public JsonResult OnPostGetTrimActualPositionZ()
        {
            return new JsonResult(mPressModule.Resources.Trim.PositionZ);
        }

        public JsonResult OnPostGetTrimSensorStatus()
        {
           bool status = new bool();
            status = mPressModule.Resources.Trim.ToolLocked;

            return new JsonResult(status);
        }
        #endregion

        #region Form
        public void OnPostFormGoToZ(string input1, string input2)
        {
            mPressModule.Resources.Form.GoTo(Convert.ToDouble(input1), Convert.ToInt32(input2));
        }

        public JsonResult OnPostGetFormActualPositionZ()
        {
            return new JsonResult(mPressModule.Resources.Form.PositionZ);
        }

        public JsonResult OnPostGetFormSensorStatus()
        {
            bool status = new bool();
            status = mPressModule.Resources.Form.ToolLocked;

            return new JsonResult(status);
        }
        #endregion

        #region Indexer

        public void OnPostIndexerLeft()
        {
            mPressModule.Resources.Indexer.ToLeft();            
        }

        public void OnPostIndexerRight()
        {
            mPressModule.Resources.Indexer.ToRight();
        }
        public void OnPostIndexerPinDown()
        {
            mPressModule.Resources.Indexer.PinDown();
        }

        public void OnPostIndexerPinUp()
        {
            mPressModule.Resources.Indexer.PinUp();
        }

        public void OnPostIndexerVacuumOn(bool[] input)
        {
            if (input.Length >= 5)
            {
                mPressModule.Resources.Indexer.VacuumOn(input);
            }
        }

        public void OnPostIndexerVacuumOff(bool[] input)
        {
            if (input.Length >= 5)
            {
                mPressModule.Resources.Indexer.VacuumOff(input);
            }
        }

        public void OnPostIndexerDeactivateBlowOff(bool[] input)
        {
            if (input.Length >= 5)
            {
                mPressModule.Resources.Indexer.DeactivateVacuumBlowOff(input);
            }
        }

        public void OnPostIndexerActivateBlowOff(bool[] input)
        {
            if (input.Length >= 5)
            {
                mPressModule.Resources.Indexer.ActivateVacuumBlowOff(input);
            }
        }

        public JsonResult OnPostGetIndexerSensorValues()
        {
            List<bool> sensorStatusses = new()
            {
                mPressModule.Resources.Indexer.IsOnInfeed,
                mPressModule.Resources.Indexer.IsOnOutfeed,
                mPressModule.Resources.Indexer.IsUp,
                mPressModule.Resources.Indexer.IsDown,
                mPressModule.Resources.Indexer.IsVacuum1On,
                mPressModule.Resources.Indexer.IsVacuum2On,
                mPressModule.Resources.Indexer.IsVacuum3On,
                mPressModule.Resources.Indexer.IsVacuum4On,
                mPressModule.Resources.Indexer.IsVacuum5On,

Modules/PressModule.HMI/Pages/Setup/PressModule/Subprocesses/_FormingSettingsPartial.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<form method="post">
        <button class="button" id="CloseSetupForming" title="Close settings" style="float:right; width:50px; height:50px">
        <img src="/_content/Platform.HMI/icons/close.png" style="width:35px; padding:1px" />
        </button>
    </form>
    <form method="post">
        <h2>Form settings</h2>
        <div>&nbsp;</div>
        <div class="settings-card">
            <div class="row">
                <label for="FormTopPosition" class="col-5">Top position</label>
                <input class="textbox" id="FormTopPosition" name="FormTopPosition" type="number" value="@Model.FormingSettingsModel.FormTopPosition.ToString("F2")" min="1.00" max="1025.00" step="0.01" data-decimal="2" oninput="enforceNumberValidation(this)"/>
                <label for="FormTopPosition">mm</label>
            </div>
            <div class="row">
                <label for="FormClosePosition" class="col-5">Close position</label>
            <input class="textbox" id="FormClosePosition" name="FormClosePosition" type="number" value="@Model.FormingSettingsModel.FormClosePosition.ToString("F2")" min="1.00" max="225.00" step="0.01" data-decimal="2" oninput="enforceNumberValidation(this)" />
                <label for="FormClosePosition">mm</label>
            </div>
             <div class="row">
                <label for="FormSafePosition" class="col-5">Safe position</label>
            <input class="textbox" id="FormSafePosition" name="FormSafePosition" type="number" value="@Model.FormingSettingsModel.FormSafePosition.ToString("F2")" min="1.00" max="225.00" step="0.01" data-decimal="2" oninput="enforceNumberValidation(this)" />
                <label for="FormSafePosition">mm</label>
            </div>
            <div class="row">
                <label for="FormRemovePosition" class="col-5">Remove position</label>
            <input class="textbox" id="FormRemovePosition" name="FormRemovePosition" type="number" value="@Model.FormingSettingsModel.FormRemovePosition.ToString("F2")" min="1.00" max="225.00" step="0.01" data-decimal="2" oninput="enforceNumberValidation(this)" />
                <label for="FormRemovePosition">mm</label>
            </div>
            <div class="row">
                <label for="FormMaintenancePosition" class="col-5">Maintenance position</label>
            <input class="textbox" id="FormMaintenancePosition" name="FormMaintenancePosition" type="number" value="@Model.FormingSettingsModel.FormMaintenancePosition.ToString("F2")" min="1.00" max="225.00" step="0.01" data-decimal="2" oninput="enforceNumberValidation(this)" />
                <label for="FormMaintenancePosition">mm</label>
            </div>
            <div class="row">
                <label for="FormVelocity" class="col-5">Velocity</label>
            <input class="textbox" id="FormVelocity" name="FormVelocity" type="number" value="@Model.FormingSettingsModel.FormVelocity" min="1" max="150" step="1" data-decimal="0" oninput="enforceNumberValidation(this)" />
                <label for="FormVelocity">mm/s</label>
            </div>
        </div>
        <div>&nbsp;</div>
        <div class="text-center">
            <button class="button" asp-page-handler="DownloadFormingSettingsToPLC" title="Download to PLC">
            <img src="/_content/Platform.HMI/icons/download.png" width="30">
            </button>
            <button class="button" asp-page-handler="SaveFormingSettings" title="Save to database">
            <img src="/_content/Platform.HMI/icons/save.png" width="30">
            </button>
            <button class="button" asp-page-handler="RefreshFormingSettingsFromRecipe" title="Load from database">
            <img src="/_content/Platform.HMI/icons/back.png" width="30">
            </button>
        </div>
    </form>

Modules/PressModule.HMI/Pages/Setup/PressModule/Subprocesses/_TrimmingSettingsPartial.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<form method="post">
        <button class="button" id="CloseSetupTrimming" title="Close settings" style="float:right; width:50px; height:50px">
            <img src="/_content/Platform.HMI/icons/close.png" style="width:35px; padding:1px" />
        </button>
    </form>
    <form method="post">
    <h2>Trimming settings</h2>
    <div>&nbsp;</div>
    <div class="settings-card">

        <div class="row">
            <label for="TrimTopPosition" class="col-5">Top position</label>
            <input class="textbox" id="TrimTopPosition" name="TrimTopPosition" type="number" value="@Model.TrimmingSettingsModel.TrimTopPosition.ToString("F2")" " min="1" max="1025" step="0.01" data-decimal="2" oninput="enforceNumberValidation(this)" />
            <label for="TopPosition">mm</label>
        </div>
        <div class="row">
            <label for="TrimClosePosition" class="col-5">Close position</label>
            <input class="textbox" id="TrimClosePosition" name="TrimClosePosition" type="number" value="@Model.TrimmingSettingsModel.TrimClosePosition.ToString("F2")" " min="1.00" max="225.00" step="0.01" data-decimal="2" oninput="enforceNumberValidation(this)" />
            <label for="TrimClosePosition">mm</label>
        </div>
        <div class="row">
            <label for="TrimSafePositionZ" class="col-5">Safe position z</label>
            <input class="textbox" id="TrimSafePositionZ" name="TrimSafePosition" type="number" value="@Model.TrimmingSettingsModel.TrimSafePosition.ToString("F2")" " min="1.00" max="225.00" step="0.01" data-decimal="2" oninput="enforceNumberValidation(this)" />
            <label for="TrimSafePositionZ">mm</label>
        </div>
        <div class="row">
            <label for="TrimRemovePosition" class="col-5">Remove position</label>
            <input class="textbox" id="TrimRemovePosition" name="TrimRemovePosition" type="number" value="@Model.TrimmingSettingsModel.TrimRemovePosition.ToString("F2")" " min="1" max="225" step="0.01" data-decimal="2" oninput="enforceNumberValidation(this)" />
            <label for="TrimRemovePosition">mm</label>
        </div>
        <div class="row">
            <label for="TrimMaintenancePosition" class="col-5">Maintenance position</label>
            <input class="textbox" id="TrimMaintenancePosition" name="TrimMaintenancePosition" type="number" value="@Model.TrimmingSettingsModel.TrimMaintenancePosition.ToString("F2")" " min="1.00" max="225.00" step="0.01" data-decimal="2" oninput="enforceNumberValidation(this)" />
            <label for="TrimMaintenancePosition">mm</label>
        </div>
        <div class="row">
            <label for="TrimVelocity" class="col-5">Velocity</label>
            <input class="textbox" id="TrimVelocity" name="TrimVelocity" type="number" value="@Model.TrimmingSettingsModel.TrimVelocity" min="1" max="150" step="1" data-decimal="0" oninput="enforceNumberValidation(this)" />
            <label for="Velocity">mm/s</label>
        </div>
    </div>
    <div>&nbsp;</div>
    <div class="text-center">
        <button class="button" asp-page-handler="DownloadTrimmingSettingsToPLC" title="Download to PLC">
            <img src="/_content/Platform.HMI/icons/download.png" width="30">
        </button>
        <button class="button" asp-page-handler="SaveTrimmingSettings" title="Save to database">
            <img src="/_content/Platform.HMI/icons/save.png" width="30">
        </button>
        <button class="button" asp-page-handler="RefreshTrimmingSettingsFromRecipe" title="Load from database">
            <img src="/_content/Platform.HMI/icons/back.png" width="30">
        </button>
    </div>
</form>

Modules/PressModule.HMI/Pages/Setup/PressModule/Subprocesses/_WasteHandlerSettingsPartial.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<form method="post">
    <button class="button" id="CloseSetupWasteHandler" title="Close settings" style="float:right; width:50px; height:50px">
        <img src="/_content/Platform.HMI/icons/close.png" style="width:35px; padding:1px" />
    </button>
</form>
<form method="post">
    <h2>Waste handler settings</h2>
    <div>&nbsp;</div>
    <div class="settings-card">
        <div class="row">
            <label for="AlmostMaxiumWasteCount" class="col-5">Almost full count</label>
            <input class="textbox" id="AlmostFullCount" name="AlmostFullCount" type="number" value="@Model.WasteHandlerSettingsModel.AlmostFullCount" min="1" max="1000" step="1" />
            <label for="AlmostFullCount">#</label>
        </div>
        <div class="row">
            <label for="MaximumWasteCount" class="col-5">Maximum waste count </label>
            <input class="textbox" id="MaximumWasteCount" name="MaximumWasteCount" type="number" value="@Model.WasteHandlerSettingsModel.MaximumWasteCount" min="1" max="1000" step="1" />
            <label for="MaximumWasteCount">#</label>
        </div>
    </div>
    <div>&nbsp;</div>
    <div class="text-center">
        <button class="button" asp-page-handler="DownloadWasteHandlerSettingsToPLC" title="Download to PLC">
            <img src="/_content/Platform.HMI/icons/download.png" width="30">
        </button>
        <button class="button" asp-page-handler="SaveWasteHandlerSettings" title="Save to database">
            <img src="/_content/Platform.HMI/icons/save.png" width="30">
        </button>
        <button class="button" asp-page-handler="RefreshWasteHandlerSettingsFromRecipe" title="Load from database">
            <img src="/_content/Platform.HMI/icons/back.png" width="30">
        </button>
    </div>
    <div>&nbsp;</div>
</form>

<div class="settings-card">
    <div class="row col-12">
        <label for="WastebinCount" class="col-4">Count</label>
        <div class="row col-7">
            <input class="textbox" id="WasteHandlerBinCount" disabled />
            <label for="WasteBinCount">#</label>
        </div>
        <div class="col-1">
            <button class="halvebutton" id="ExecuteResetCounterButton" title="Reset to zero">
                <img src="/_content/Platform.HMI/icons/arrow_right.png" width="35" />
                0
            </button>
        </div>
    </div>
</div>

<script>
    $("#ExecuteResetCounterButton").click(function (e) {
        e.preventDefault();
        sendCommand("SetupPressModule", "ResetWasteBinCounter");
    });
</script>