Modules/MagazineLoader.HMI/Pages/Setup/MagazineLoader/SetupMagazineLoader.cshtml.cs
using Authorization.Lib;
using MagazineLoader;
using MagazineLoader.Application;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Platform.HMI.Resources;
using Platform.Lib;
using Power_X1_iCT.Model;

namespace Power_X1_iCT.Pages.Setup
{
    [BindProperties]
    [Authorize(Policy = SetupPolicy.Name)]
    public class SetupMagazineLoaderModel : PageModel
    {
        private readonly ILogger mLog;
        private readonly MagazineLoaderUpdater mUpdater;
        private MagazineLoaderModule mMagazineLoaderModule = MagazineLoaderModule.Instance;

        public MagazineLoaderSettingsModel MagazineLoaderSettingsModel { get; set; }

        public LoadMagazineSettingsModel LoadMagazineSettingsModel { get; set; }

        public ProvideMaterialSettingsModel ProvideMaterialSettingsModel { get; set; }

        public UnloadMagazineSettingsModel UnloadMagazineSettingsModel { get; set; }

        public bool SimulationEnabled { get; set; }

        public bool IsRunningProduction { get; set; }

        public SetupMagazineLoaderModel(MagazineLoaderUpdater magazineLoaderUpdater, ILogger<SetupMagazineLoaderModel> logger)
        {
            mLog = logger;
            mUpdater = magazineLoaderUpdater;
            MagazineLoaderSettingsModel = new MagazineLoaderSettingsModel();
            LoadMagazineSettingsModel = new LoadMagazineSettingsModel();
            ProvideMaterialSettingsModel = new ProvideMaterialSettingsModel();
            UnloadMagazineSettingsModel = new UnloadMagazineSettingsModel();

            mMagazineLoaderModule.SimulationChanged += MagazineLoaderModule_SimulationChanged;
            MagazineLoaderModule_SimulationChanged(this, mMagazineLoaderModule.InSimulation);
        }

        private void MagazineLoaderModule_SimulationChanged(object? sender, bool e)
        {
            SimulationEnabled = e;
        }

        public JsonResult OnPostGetState()
        {
            return new JsonResult(new { state = ((State)mMagazineLoaderModule.State).ToString() });
        }

        public JsonResult OnPostGetStatusses()
        {
            return mUpdater.GetStatusses();
        }

        public JsonResult OnPostGetSimulationEnabled()
        {
            return new JsonResult(mMagazineLoaderModule.InSimulation);
        }

        public void OnPostInitialize()
        {
            mLog.LogInformation("OnInitialize");
            mMagazineLoaderModule.Initialize();
        }
        public JsonResult OnPostCanStart()
        {
            return new JsonResult(mMagazineLoaderModule.CanStart());
        }

        public void OnPostStart()
        {
            mMagazineLoaderModule.Start();
        }
        public JsonResult OnPostCanStop()
        {
            return new JsonResult(mMagazineLoaderModule.CanStop());
        }

        public void OnPostStop()
        {
            mMagazineLoaderModule.Stop();
        }
        public JsonResult OnPostCanProcessCommands()
        {
            var canProcess = !mMagazineLoaderModule.IsRunningProduction &&
                mMagazineLoaderModule.State == (int)State.Running &&
                mMagazineLoaderModule.Status != (int)StatusBar.Status.Busy;
            return new JsonResult(canProcess);

        }

        public void OnPostLoadMagazine()
        {
            mMagazineLoaderModule.ExecuteLoadMagazine();
        }

        public void OnPostProvideMaterial()
        {
            mMagazineLoaderModule.ExecuteProvideMaterial();
        }

        public void OnPostUnloadMagazine()
        {
            mMagazineLoaderModule.ExecuteUnloadMagazine();
        }
        #region Resources
        #region LowerHatch
        public void OnPostLowerHatchOpen()
        {
            mMagazineLoaderModule.Resources.LowerHatch.HatchOpen();
        }

        public void OnPostLowerHatchClose()
        {
            mMagazineLoaderModule.Resources.LowerHatch.HatchClose();
        }

        public JsonResult OnPostGetLowerHatchSensorValues()
        {
            bool[] sensorStatusses = new bool[2];
            sensorStatusses[0] = mMagazineLoaderModule.Resources.LowerHatch.HatchIsOpen;
            sensorStatusses[1] = mMagazineLoaderModule.Resources.LowerHatch.HatchIsClosed;

            return new JsonResult(sensorStatusses);
        }
        #endregion

        #region LowerConveyor
        public void OnPostLowerConveyorStart()
        {
            mMagazineLoaderModule.Resources.LowerConveyor.ConveyorStart();
        }

        public void OnPostLowerConveyorStop()
        {
            mMagazineLoaderModule.Resources.LowerConveyor.ConveyorStop();
        }

        public JsonResult OnPostGetLowerConveyorSensorValues()
        {
            bool[] sensorStatusses = new bool[2];
            sensorStatusses[0] = mMagazineLoaderModule.Resources.LowerConveyor.MagazinePresent;
            sensorStatusses[1] = mMagazineLoaderModule.Resources.LowerConveyor.ConveyorFull;

            return new JsonResult(sensorStatusses);
        }
        #endregion

        #region Lift      

        public void OnPostLiftGoToY(string position, string velocity)
        {
            mMagazineLoaderModule.Resources.Lift.GoTo(Convert.ToDouble(position), mMagazineLoaderModule.Resources.Lift.PositionZ, Convert.ToInt32(velocity));
        }

        public void OnPostLiftGoToZ(string position, string velocity)
        {
            mMagazineLoaderModule.Resources.Lift.GoTo(mMagazineLoaderModule.Resources.Lift.PositionY, Convert.ToDouble(position), Convert.ToInt32(velocity));
        }

        public void OnPostGripperOpen()
        {
            mMagazineLoaderModule.Resources.Lift.GripperOpen();
        }

        public void OnPostGripperClose()
        {
            mMagazineLoaderModule.Resources.Lift.GripperClose();
        }
       
        public JsonResult OnPostGetLiftActualPositionY()
        {
            return new JsonResult(mMagazineLoaderModule.Resources.Lift.PositionY);
        }


        public JsonResult OnPostGetLiftActualPositionZ()
        {
            return new JsonResult(mMagazineLoaderModule.Resources.Lift.PositionZ);
        }

        public JsonResult OnPostGetGripperSensorValues()
        {
            bool[] sensorStatusses = new bool[2];
            sensorStatusses[0] = mMagazineLoaderModule.Resources.Lift.IsGripperOpen;
            sensorStatusses[1] = mMagazineLoaderModule.Resources.Lift.IsGripperClosed;

            return new JsonResult(sensorStatusses);
        }
        #endregion

        #region Upperhatch
        public void OnPostUpperHatchOpen()
        {
            mMagazineLoaderModule.Resources.UpperHatch.HatchOpen();
        }

        public void OnPostUpperHatchClose()
        {
            mMagazineLoaderModule.Resources.UpperHatch.HatchClose();
        }

        public JsonResult OnPostGetUpperHatchSensorValues()
        {
            bool[] sensorStatusses = new bool[2];
            sensorStatusses[0] = mMagazineLoaderModule.Resources.UpperHatch.HatchIsOpen;
            sensorStatusses[1] = mMagazineLoaderModule.Resources.UpperHatch.HatchIsClosed;

            return new JsonResult(sensorStatusses);
        }
        #endregion

        #region UpperConveyor
        public void OnPostUpperConveyorStart()
        {
            mMagazineLoaderModule.Resources.UpperConveyor.ConveyorStart();
        }

        public void OnPostUpperConveyorStop()
        {
            mMagazineLoaderModule.Resources.UpperConveyor.ConveyorStop();
        }

        public JsonResult OnPostGetUpperConveyorSensorValues()
        {
            bool[] sensorStatusses = new bool[2];
            sensorStatusses[0] = mMagazineLoaderModule.Resources.UpperConveyor.MagazinePresent;
            sensorStatusses[1] = mMagazineLoaderModule.Resources.UpperConveyor.ConveyorAlmostEmpty;

            return new JsonResult(sensorStatusses);
        }
        #endregion

        #region LeadframePusher
        public JsonResult OnPostGetLeadframePusherSensorValues()
        {
            List<bool> sensorStatusses = new()
            {
                mMagazineLoaderModule.Resources.LeadFramePusher.PrimairPusherIn,
                mMagazineLoaderModule.Resources.LeadFramePusher.PrimairPusherMiddle,
                mMagazineLoaderModule.Resources.LeadFramePusher.PrimairPusherOut,
                mMagazineLoaderModule.Resources.LeadFramePusher.SecondairPusherIn,
                mMagazineLoaderModule.Resources.LeadFramePusher.SecondairPusherOut
            };

            return new JsonResult(sensorStatusses);
        }

        public void OnPostPrimairPusherRetrieve()
        {            
                mMagazineLoaderModule.Resources.LeadFramePusher.PrimairPusherRetrieve();
        }

        public void OnPostPrimairPusherPush()
        {
            mMagazineLoaderModule.Resources.LeadFramePusher.PrimairPusherPush();
        }

        public void OnPostSecondairPusherRetrieve()
        {
            mMagazineLoaderModule.Resources.LeadFramePusher.SecondairPusherRetrieve();
        }

        public void OnPostSecondairPusherPush()
        {
            mMagazineLoaderModule.Resources.LeadFramePusher.SecondairPusherPush();
        }
        #endregion

        #region Outfeed
        public JsonResult OnPostGetOutfeedSensorValues()
        {
            bool[] sensorStatusses = new bool[1];
            sensorStatusses[0] = mMagazineLoaderModule.Resources.Outfeed.ProductAtTransfer;            

            return new JsonResult(sensorStatusses);
        }
        #endregion

        #endregion
        public void OnPostDownloadLoadMagazineSettingsToPLC(LoadMagazineSettingsModel model)
        {
            model.Download();
        }               
        public IActionResult OnPostDownloadProvideMaterialSettingsToPLC()
        {
            ProvideMaterialSettingsModel.Download();

            // otherwise do some processing

Modules/MagazineLoader.HMI/Pages/Setup/MagazineLoader/Subprocesses/LoadMagazine/LoadMagazineSettingsPartial.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<form method="post">
        <button class="button" id="CloseSetupLoadMagazine" title="Close settings" style="float:right; width:50px; height:50px">
            <img src="/_content/Platform.HMI/icons/close.png" style="width:35px; padding:1px" />
        </button>
    </form>
    <form method="post">
        <h2>Load magazine settings</h2>
        <div>&nbsp;</div>
        <div class="settings-card">
            <div class="row">
                <label for="UpperConveyorZ" class="col-5">Upper conveyor Z</label>
                <input class="textbox" id="UpperConveyorZ" name="UpperConveyorZ" type="number" value="@Model.LoadMagazineSettingsModel.UpperConveyorZ.ToString("F2")" min="1.00" max="1025.00" step="0.10" />
                <label for="UpperConveyorZ">mm</label>
            </div>
            <div class="row">
                <label for="SlotCount" class="col-5">Slot count </label>
                <input class="textbox" id="SlotCount" name="SlotCount" type="number" value="@Model.LoadMagazineSettingsModel.SlotCount" min="1.00" max="25.00" step="1" />
                <label for="SlotCount">#</label>
            </div>
            <div class="row">
                <label for="StartPickOffsetZ" class="col-5">Start pick offset Z</label>
                <input class="textbox" id="StartPickOffsetZ" name="StartPickOffsetZ" type="number" value="@Model.LoadMagazineSettingsModel.StartPickOffsetZ.ToString("F2")" min="1.00" max="225.00" step="0.1" />
                <label for="StartPickOffsetZ">mm</label>
            </div>
            <div class="row">
                <label for="EndPickOffsetZ" class="col-5">End pick offset Z</label>
                <input class="textbox" id="EndPickOffsetZ" name="EndPickOffsetZ" type="number" value="@Model.LoadMagazineSettingsModel.EndPickOffsetZ.ToString("F2")" min="1.00" max="225.00" step="0.1" />
                <label for="EndPickOffsetZ">mm</label>
            </div>
            <div class="row">
                <label for="PickY" class="col-5">Pick Y</label>
                <input class="textbox" id="PickY" name="PickY" type="number" value="@Model.LoadMagazineSettingsModel.PickY.ToString("F2")" min="1.00" max="225.00" step="0.1" />
                <label for="PickY">mm</label>
            </div>
            <div class="row">
                <label for="MagazinePositionLiftSafePositionY" class="col-5">Lift safe position Y</label>
                <input class="textbox" id="MagazinePositionLiftSafePositionY" name="MagazinePositionLiftSafePositionY" type="number" value="@Model.LoadMagazineSettingsModel.MagazinePositionLiftSafePositionY.ToString("#,##0.00#")" min="1.00" max="225.00" step="0.1" />
                <label for="MagazinePositionLiftSafePositionY">mm</label>
            </div>
            <div class="row">
                <label for="LoadVelocityY" class="col-5">Velocity Y</label>
                <input class="textbox" id="LoadVelocityY" name="LoadVelocityY" type="number" value="@Model.LoadMagazineSettingsModel.LoadVelocityY.ToString("F0")" min="10.00" max="200.00" step="5" />
                <label for="LoadVelocityY">mm/s</label>
            </div>
             <div class="row">
                <label for="LoadVelocityZ" class="col-5">Velocity Z</label>
                <input class="textbox" id="LoadVelocityZ" name="LoadVelocityZ" type="number" value="@Model.LoadMagazineSettingsModel.LoadVelocityZ.ToString("F0")" min="10.00" max="200.00" step="5" />
                <label for="LoadVelocityZ">mm/s</label>
            </div>
        </div>
        <div>&nbsp;</div>
        <div class="text-center">
            <button class="button" asp-page-handler="DownloadLoadMagazineSettingsToPLC" title="Download to PLC">
                <img src="/_content/Platform.HMI/icons/download.png" width="30">
            </button>
            <button class="button" asp-page-handler="SaveLoadMagazineSettings" title="Save to database">
                <img src="/_content/Platform.HMI/icons/save.png" width="30">
            </button>
            <button class="button" asp-page-handler="RefreshLoadMagazineSettingsFromRecipe" title="Load from database">
                <img src="/_content/Platform.HMI/icons/back.png" width="30">
            </button>
        </div>
    </form>